# INTERFACE CONFIGURATION

PHYSICAL_IF=eth0
MACSEC_IF=macsec0
MACSEC_IP=1.1.1.1
MACSEC_PREFIX=24

###############################################################################
# WPA SUPPLICANT
###############################################################################

WPA_CONF=/etc/wpa_supplicant.conf
WPA_LOG=/var/log/wpa_supplicant.log

###############################################################################
# MACSEC MANAGER
###############################################################################

LOG_FILE=/var/log/macsec_manager.log

###############################################################################
# STARTUP
###############################################################################

WAIT_MACSEC_IF=10

###############################################################################
# ANALYZER
###############################################################################

PCAP_DIR=/tmp
