eapol_version=3
ap_scan=0
fast_reauth=1

network={
        key_mgmt=NONE
        eapol_flags=0
        macsec_policy=1

        mka_cak=68126c8a8914d7b39c64f7b294e29f12
        mka_ckn=9ff7ed8e78d30f8cbb44f585d5a88fbd586e21fdaeda46c9a34adea618c92fdd
}

